# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: template.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='template.proto',
  package='github.com.tinkerbell.tink.protos.template',
  syntax='proto3',
  serialized_options=b'Z*github.com/tinkerbell/tink/protos/template',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0etemplate.proto\x12*github.com.tinkerbell.tink.protos.template\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x07\n\x05\x45mpty\"\xd0\x01\n\x10WorkflowTemplate\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12.\n\ncreated_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\ndeleted_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0c\n\x04\x64\x61ta\x18\x07 \x01(\tJ\x04\x08\x03\x10\x04\"\x1c\n\x0e\x43reateResponse\x12\n\n\x02id\x18\x01 \x01(\t\"4\n\nGetRequest\x12\x0c\n\x02id\x18\x01 \x01(\tH\x00\x12\x0e\n\x04name\x18\x02 \x01(\tH\x00\x42\x08\n\x06get_by\"*\n\x0bListRequest\x12\x0e\n\x04name\x18\x01 \x01(\tH\x00\x42\x0b\n\tfilter_by2\x9a\x06\n\x0fTemplateService\x12\xa4\x01\n\x0e\x43reateTemplate\x12<.github.com.tinkerbell.tink.protos.template.WorkflowTemplate\x1a:.github.com.tinkerbell.tink.protos.template.CreateResponse\"\x18\x82\xd3\xe4\x93\x02\x12\"\r/v1/templates:\x01*\x12\x9f\x01\n\x0bGetTemplate\x12\x36.github.com.tinkerbell.tink.protos.template.GetRequest\x1a<.github.com.tinkerbell.tink.protos.template.WorkflowTemplate\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/templates/{id}\x12\x97\x01\n\x0e\x44\x65leteTemplate\x12\x36.github.com.tinkerbell.tink.protos.template.GetRequest\x1a\x31.github.com.tinkerbell.tink.protos.template.Empty\"\x1a\x82\xd3\xe4\x93\x02\x14*\x12/v1/templates/{id}\x12\x9f\x01\n\rListTemplates\x12\x37.github.com.tinkerbell.tink.protos.template.ListRequest\x1a<.github.com.tinkerbell.tink.protos.template.WorkflowTemplate\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/templates0\x01\x12\x81\x01\n\x0eUpdateTemplate\x12<.github.com.tinkerbell.tink.protos.template.WorkflowTemplate\x1a\x31.github.com.tinkerbell.tink.protos.template.EmptyB,Z*github.com/tinkerbell/tink/protos/templateb\x06proto3'
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='github.com.tinkerbell.tink.protos.template.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=132,
)


_WORKFLOWTEMPLATE = _descriptor.Descriptor(
  name='WorkflowTemplate',
  full_name='github.com.tinkerbell.tink.protos.template.WorkflowTemplate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='github.com.tinkerbell.tink.protos.template.WorkflowTemplate.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='github.com.tinkerbell.tink.protos.template.WorkflowTemplate.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='created_at', full_name='github.com.tinkerbell.tink.protos.template.WorkflowTemplate.created_at', index=2,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='updated_at', full_name='github.com.tinkerbell.tink.protos.template.WorkflowTemplate.updated_at', index=3,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='deleted_at', full_name='github.com.tinkerbell.tink.protos.template.WorkflowTemplate.deleted_at', index=4,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='github.com.tinkerbell.tink.protos.template.WorkflowTemplate.data', index=5,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=343,
)


_CREATERESPONSE = _descriptor.Descriptor(
  name='CreateResponse',
  full_name='github.com.tinkerbell.tink.protos.template.CreateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='github.com.tinkerbell.tink.protos.template.CreateResponse.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=345,
  serialized_end=373,
)


_GETREQUEST = _descriptor.Descriptor(
  name='GetRequest',
  full_name='github.com.tinkerbell.tink.protos.template.GetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='github.com.tinkerbell.tink.protos.template.GetRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='github.com.tinkerbell.tink.protos.template.GetRequest.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='get_by', full_name='github.com.tinkerbell.tink.protos.template.GetRequest.get_by',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=375,
  serialized_end=427,
)


_LISTREQUEST = _descriptor.Descriptor(
  name='ListRequest',
  full_name='github.com.tinkerbell.tink.protos.template.ListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='github.com.tinkerbell.tink.protos.template.ListRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='filter_by', full_name='github.com.tinkerbell.tink.protos.template.ListRequest.filter_by',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=429,
  serialized_end=471,
)

_WORKFLOWTEMPLATE.fields_by_name['created_at'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_WORKFLOWTEMPLATE.fields_by_name['updated_at'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_WORKFLOWTEMPLATE.fields_by_name['deleted_at'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_GETREQUEST.oneofs_by_name['get_by'].fields.append(
  _GETREQUEST.fields_by_name['id'])
_GETREQUEST.fields_by_name['id'].containing_oneof = _GETREQUEST.oneofs_by_name['get_by']
_GETREQUEST.oneofs_by_name['get_by'].fields.append(
  _GETREQUEST.fields_by_name['name'])
_GETREQUEST.fields_by_name['name'].containing_oneof = _GETREQUEST.oneofs_by_name['get_by']
_LISTREQUEST.oneofs_by_name['filter_by'].fields.append(
  _LISTREQUEST.fields_by_name['name'])
_LISTREQUEST.fields_by_name['name'].containing_oneof = _LISTREQUEST.oneofs_by_name['filter_by']
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['WorkflowTemplate'] = _WORKFLOWTEMPLATE
DESCRIPTOR.message_types_by_name['CreateResponse'] = _CREATERESPONSE
DESCRIPTOR.message_types_by_name['GetRequest'] = _GETREQUEST
DESCRIPTOR.message_types_by_name['ListRequest'] = _LISTREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'template_pb2'
  # @@protoc_insertion_point(class_scope:github.com.tinkerbell.tink.protos.template.Empty)
  })
_sym_db.RegisterMessage(Empty)

WorkflowTemplate = _reflection.GeneratedProtocolMessageType('WorkflowTemplate', (_message.Message,), {
  'DESCRIPTOR' : _WORKFLOWTEMPLATE,
  '__module__' : 'template_pb2'
  # @@protoc_insertion_point(class_scope:github.com.tinkerbell.tink.protos.template.WorkflowTemplate)
  })
_sym_db.RegisterMessage(WorkflowTemplate)

CreateResponse = _reflection.GeneratedProtocolMessageType('CreateResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATERESPONSE,
  '__module__' : 'template_pb2'
  # @@protoc_insertion_point(class_scope:github.com.tinkerbell.tink.protos.template.CreateResponse)
  })
_sym_db.RegisterMessage(CreateResponse)

GetRequest = _reflection.GeneratedProtocolMessageType('GetRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETREQUEST,
  '__module__' : 'template_pb2'
  # @@protoc_insertion_point(class_scope:github.com.tinkerbell.tink.protos.template.GetRequest)
  })
_sym_db.RegisterMessage(GetRequest)

ListRequest = _reflection.GeneratedProtocolMessageType('ListRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTREQUEST,
  '__module__' : 'template_pb2'
  # @@protoc_insertion_point(class_scope:github.com.tinkerbell.tink.protos.template.ListRequest)
  })
_sym_db.RegisterMessage(ListRequest)


DESCRIPTOR._options = None

_TEMPLATESERVICE = _descriptor.ServiceDescriptor(
  name='TemplateService',
  full_name='github.com.tinkerbell.tink.protos.template.TemplateService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=474,
  serialized_end=1268,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateTemplate',
    full_name='github.com.tinkerbell.tink.protos.template.TemplateService.CreateTemplate',
    index=0,
    containing_service=None,
    input_type=_WORKFLOWTEMPLATE,
    output_type=_CREATERESPONSE,
    serialized_options=b'\202\323\344\223\002\022\"\r/v1/templates:\001*',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetTemplate',
    full_name='github.com.tinkerbell.tink.protos.template.TemplateService.GetTemplate',
    index=1,
    containing_service=None,
    input_type=_GETREQUEST,
    output_type=_WORKFLOWTEMPLATE,
    serialized_options=b'\202\323\344\223\002\024\022\022/v1/templates/{id}',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteTemplate',
    full_name='github.com.tinkerbell.tink.protos.template.TemplateService.DeleteTemplate',
    index=2,
    containing_service=None,
    input_type=_GETREQUEST,
    output_type=_EMPTY,
    serialized_options=b'\202\323\344\223\002\024*\022/v1/templates/{id}',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ListTemplates',
    full_name='github.com.tinkerbell.tink.protos.template.TemplateService.ListTemplates',
    index=3,
    containing_service=None,
    input_type=_LISTREQUEST,
    output_type=_WORKFLOWTEMPLATE,
    serialized_options=b'\202\323\344\223\002\017\022\r/v1/templates',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateTemplate',
    full_name='github.com.tinkerbell.tink.protos.template.TemplateService.UpdateTemplate',
    index=4,
    containing_service=None,
    input_type=_WORKFLOWTEMPLATE,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TEMPLATESERVICE)

DESCRIPTOR.services_by_name['TemplateService'] = _TEMPLATESERVICE

# @@protoc_insertion_point(module_scope)
